# -*- coding: utf-8 -*-
# Generated by Django 1.11.6 on 2024-04-20 01:27
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Categories',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=150, verbose_name='Nombre')),
                ('created', models.DateTimeField(auto_now_add=True)),
                ('updated', models.DateTimeField(auto_now=True)),
                ('minimum_age', models.IntegerField(verbose_name='Edad Minima')),
            ],
            options={
                'verbose_name': 'Categoria',
                'verbose_name_plural': 'Especialidades',
            },
        ),
        migrations.CreateModel(
            name='Movies',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=150, verbose_name='Nombre')),
                ('created', models.DateTimeField(auto_now_add=True)),
                ('updated', models.DateTimeField(auto_now=True)),
                ('description', models.CharField(max_length=256, verbose_name='Teléfono')),
                ('image', models.ImageField(upload_to='movies', verbose_name='Imagen Carnet')),
                ('release_date', models.DateField(verbose_name='Fecha de atención')),
                ('category', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='movies.Categories', verbose_name='Reserva')),
            ],
            options={
                'verbose_name': 'Reserva',
                'verbose_name_plural': 'Reservas',
            },
        ),
    ]
